USE BK14
-- kiểm tra tổng khách hàng theo chi nhánh,theo khu vực, theo ngành nghề
SELECT 
	kh.MA_CHINHANH,
	cn.TEN_CHINHANH,
	kv.MA_KHUVUC,
	kv.TEN_KHUVUC,
	nn.MA_NGANHNGHE,
	nn.TEN_NGANHNGHE,
	COUNT(kh.MA_KHACHHANG) AS SOKHACHHANG
FROM TBL_KHACH_HANG kh
INNER JOIN TBL_CHINHANH cn ON kh.MA_CHINHANH = cn.MA_CHINHANH
INNER JOIN TBL_DANHMUC_NGANHNGHE nn ON kh.MA_NGANHNGHE = nn.MA_NGANHNGHE
INNER JOIN TBL_KHUVUC kv ON cn.MA_KHUVUC = kv.MA_KHUVUC
GROUP BY kh.MA_CHINHANH, cn.TEN_CHINHANH, kv.MA_KHUVUC, kv.TEN_KHUVUC, nn.MA_NGANHNGHE, nn.TEN_NGANHNGHE