-- Kiểm tra tài sản bảo đảm, tỷ lệ che phủ dư nợ, hợp đồng thiếu bảo đảm
WITH Repayment AS (
    SELECT
        MA_HOPDONG_TINDUNG,
        SUM(ISNULL(TRA_GOC, 0)) AS TONG_GOC_DA_TRA,
        SUM(ISNULL(TRA_LAI, 0)) AS TONG_LAI_DA_TRA
    FROM TBL_THUHOINO
    GROUP BY MA_HOPDONG_TINDUNG
),

Loan AS (
    SELECT
        hd.MA_HOPDONG_TINDUNG,
        hd.MA_KHACHHANG,
        hd.SOTIEN_GIAINGAN,
        ISNULL(r.TONG_GOC_DA_TRA, 0) AS TONG_GOC_DA_TRA,
        ISNULL(r.TONG_LAI_DA_TRA, 0) AS TONG_LAI_DA_TRA,
        hd.SOTIEN_GIAINGAN - ISNULL(r.TONG_GOC_DA_TRA, 0) AS DU_NO_GOC
    FROM TBL_HOPDONG_TINDUNG hd
    LEFT JOIN Repayment r
        ON hd.MA_HOPDONG_TINDUNG = r.MA_HOPDONG_TINDUNG
),

Collateral AS (
    SELECT
        MA_HOPDONG_TINDUNG,
        SUM(ISNULL(GIATRI_TAISAN, 0)) AS TONG_GIATRI_TAISAN
    FROM TBL_TAISAN_BAODAM
    GROUP BY MA_HOPDONG_TINDUNG
)

SELECT
    l.MA_HOPDONG_TINDUNG,
    l.MA_KHACHHANG,
    l.SOTIEN_GIAINGAN,
    l.TONG_GOC_DA_TRA,
    l.DU_NO_GOC,
    ISNULL(c.TONG_GIATRI_TAISAN, 0) AS TONG_GIATRI_TAISAN,
    ISNULL(c.TONG_GIATRI_TAISAN, 0) * 1.0 / NULLIF(l.DU_NO_GOC, 0) AS TYLE_CHEPHU_DUNO,
    CASE
        WHEN l.DU_NO_GOC > 0 
             AND ISNULL(c.TONG_GIATRI_TAISAN, 0) < l.DU_NO_GOC
        THEN N'Thiếu bảo đảm'
        ELSE N'Đủ bảo đảm'
    END AS TRANGTHAI_BAODAM
FROM Loan l
LEFT JOIN Collateral c
    ON l.MA_HOPDONG_TINDUNG = c.MA_HOPDONG_TINDUNG
WHERE l.DU_NO_GOC > 0
ORDER BY TYLE_CHEPHU_DUNO ASC;
