USE BK14
--FactCurrentAccountTransaction
CREATE OR ALTER VIEW VW_FactCurrentAccountTransaction AS
SELECT
    kh.MA_KHACHHANG,
    kh.MA_CHINHANH,

    CAST(tgtt.THOIGIAN_GIAODICH AS DATE) AS TransactionDate,
    EOMONTH (tgtt.THOIGIAN_GIAODICH) AS NGAYCUOITHANG,
    ISNULL(tgtt.SOTIEN_TANG, 0) AS InflowAmount,
    ISNULL(tgtt.SOTIEN_GIAM, 0) AS OutflowAmount,
    ISNULL(tgtt.SOTIEN_TANG, 0) - ISNULL(tgtt.SOTIEN_GIAM, 0) AS NetAmount

FROM TBL_TIENGUI_THANHTOAN tgtt
LEFT JOIN TBL_KHACH_HANG kh
    ON tgtt.MA_TAIKHOAN_THANHTOAN = kh.MA_TAIKHOAN_THANHTOAN

--FactSavingsDeposit
CREATE OR ALTER VIEW VW_FactSavingsDeposit 
AS
SELECT kh.MA_KHACHHANG,  
       kh.MA_CHINHANH,
       kh.MA_NGANHNGHE,
       tk.MA_TKTK,
       tk.LAI_SUAT*tk.KYHAN*tk.SOTIEN_GUI/100 AS LAIPHAITRA,
       tk.TATTOAN,
       CASE 
           WHEN tk.KYHAN<=1 THEN N'Không kỳ hạn / 1 tháng'
           WHEN tk.KYHAN<=3 THEN N'Ngắn hạn'
           WHEN tk.KYHAN<=6 THEN N'Trung hạn'
           WHEN tk.KYHAN<=12 THEN N'Dài hạn'
           ELSE N'Trên 12 tháng'
       END AS "Nhóm kỳ hạn",
       EOMONTH (tk.NGAY_GUI) AS NGAYGUICUOITHANG,
       EOMONTH(tk.NGAY_DAOHAN) AS NGAYDAOHANCUOITHANG,
       ISNULL(tk.SOTIEN_GUI,0) AS SOTIEN_GUI

FROM TBL_TIENGUI_TIETKIEM tk
LEFT JOIN TBL_KHACH_HANG kh ON kh.MA_KHACHHANG = tk.MA_KHACHHANG

--FactMobilizationPlan
CREATE OR ALTER VIEW VW_FactMobilizationPlan 
AS
SELECT *
FROM TBL_KEHOACH_HUYDONG
--FactLoanContract
CREATE OR ALTER VIEW VW_FactLoanContract 
AS
SELECT th.MA_HOPDONG_TINDUNG,
       kh.MA_KHACHHANG,
       kh.MA_CHINHANH,
       kh.MA_NGANHNGHE,
       ISNULL(hdtd.SOTIEN_GIAINGAN,0)AS SOTIEN_GIAINGAN,
       ISNULL(th.TRA_GOC,0 ) AS TRA_GOC,
       ISNULL(th.TRA_LAI,0) AS TRA_LAI,
       
       EOMONTH(th.NGAY_TRA) AS NGAYTRACUOITHANG
FROM TBL_THUHOINO th 
LEFT JOIN TBL_HOPDONG_TINDUNG hdtd ON hdtd.MA_HOPDONG_TINDUNG = th.MA_HOPDONG_TINDUNG
LEFT JOIN TBL_KHACH_HANG kh ON kh.MA_KHACHHANG = hdtd.MA_KHACHHANG

-- FactCollateral
CREATE OR ALTER VIEW VW_FactCollateral
AS
SELECT ts.MA_HOPDONG_TINDUNG,
       kh.MA_KHACHHANG,
       kh.MA_CHINHANH,
       MA_TP,
      
       ISNULL(ts.GIATRI_TAISAN,0) AS GIATRI_TAISAN
FROM TBL_TAISAN_BAODAM ts
LEFT JOIN TBL_HOPDONG_TINDUNG hdtd ON hdtd.MA_HOPDONG_TINDUNG = ts.MA_HOPDONG_TINDUNG
LEFT JOIN TBL_KHACH_HANG kh ON kh.MA_KHACHHANG = hdtd.MA_KHACHHANG
--FactCustomerBranch
CREATE OR ALTER VIEW VW_FactCustomerBranch
AS
SELECT TOP 10 cn.MA_CHINHANH,
       COUNT(DISTINCT MA_KHACHHANG) AS SOKHACHHANG
FROM TBL_KHACH_HANG kh
LEFT JOIN TBL_CHINHANH cn ON kh.MA_CHINHANH = cn.MA_CHINHANH
GROUP BY cn.MA_CHINHANH
ORDER BY SOKHACHHANG DESC