-- Check row count
SELECT 'TBL_KHACH_HANG' AS TableName, COUNT(*) FROM TBL_KHACH_HANG
UNION ALL
SELECT 'TBL_TIENGUI_THANHTOAN', COUNT(*) FROM TBL_TIENGUI_THANHTOAN
UNION ALL
SELECT 'TBL_TIENGUI_TIETKIEM', COUNT(*) FROM TBL_TIENGUI_TIETKIEM
UNION ALL
SELECT 'TBL_HOPDONG_TINDUNG', COUNT(*) FROM TBL_HOPDONG_TINDUNG
UNION ALL
SELECT 'TBL_TAISAN_BAODAM', COUNT(*) FROM TBL_TAISAN_BAODAM;

-- Check missing customer branch
SELECT *
FROM TBL_KHACH_HANG
WHERE MA_CHINHANH IS NULL;

-- Check negative amount
SELECT *
FROM TBL_TIENGUI_THANHTOAN
WHERE SOTIEN_TANG < 0 OR SOTIEN_GIAM < 0;

-- Check loan outstanding
SELECT
    hd.MA_HOPDONG_TINDUNG,
    hd.SOTIEN_GIAINGAN,
    ISNULL(SUM(th.TRA_GOC), 0) AS TotalPrincipalPaid,
    hd.SOTIEN_GIAINGAN - ISNULL(SUM(th.TRA_GOC), 0) AS OutstandingPrincipal
FROM TBL_HOPDONG_TINDUNG hd
LEFT JOIN TBL_THUHOINO th
    ON hd.MA_HOPDONG_TINDUNG = th.MA_HOPDONG_TINDUNG
GROUP BY
    hd.MA_HOPDONG_TINDUNG,
    hd.SOTIEN_GIAINGAN;
